### ISSUE TITLE
Using an old unsupported terraform-provider-vcd version 3.2.0 - request to upgrade

### ISSUE THREAD

**Issue by lvirbalas** [ibm-cloud-architecture/terraform-openshift4-vcd#58]
Hello,

I am from VMware's Terraform VCD Provider team. We have noticed that terraform-openshift4-vcd project is using a very old 3.2.0 VCD provider version:
https://github.com/ibm-cloud-architecture/terraform-openshift4-vcd/blob/master/versions.tf

This 3.2.0 version has been released back in 2021-03-10 and it will soon be two years old. This was the last version that supported VCD 9.7.

There has been multiple new versions released with numerous bugfixes and improvements since then. Please upgrade to a more recent version based on which VCD you have to support. I'm providing a list with supported VCD versions for easier reference and highlighting the highest provider version for a specific VCD release:

- **3.2.0 | 2021-03-10 | 9.7+ (v32.0)**, OpenShift on IBM Cloud
- 3.3.1 | 2021-07-05 |10.0+ (v33.0)
- 3.4.0 | 2021-09-30 | 10.0+ (v33.0)
- **3.5.1 | 2022-01-13 | 10.0+ (v33.0)**
- 3.6.0 | 2022-04-14 | 10.2+ (v35.0)
- **3.7.0 | 2022-08-02 | 10.2+ (v35.0)**
- **3.8.2 | 2023-01-12 | 10.3+ (v36.0)**

Is there any particular reason to use 3.2.0 still?

**Comment by slipsibm** [comment]
I will take a look. There is no particular reason that I know of that it needs to stay at 3.2. Are there any issues that you know of (depreciations, etc.) that I should watch out for?

**Comment by lvirbalas** [comment]
There were some. Please search for "deprecat" in the changelog for the versions you will jump through:
https://github.com/vmware/terraform-provider-vcd/blob/main/CHANGELOG.md

**Comment by slipsibm** [comment]
upgraded to 3.7.0 as would have to do a some work to fix vm definitions if i went higher

**Comment by lvirbalas** [comment]
@slipsibm may I ask which version of the provider are you using currently? Note that we have released 3.10.0 Today:
https://github.com/vmware/terraform-provider-vcd/blob/main/CHANGELOG.md#3100-july-20-2023

**Comment by slipsibm** [comment]
its still 3.7.0 When I tried going higher last time, it seemed that there were changes that needed to be made to VM creation. I can take a look and see how much work it would be to make changes

**Comment by Didainius** [comment]
@slipsibm , 
Would be curious to see what errors you get with higher than `3.7.0` - are there any schema issues or is it that the deployment itself fails?
